#!/bin/sh

readonly LIBINGER=".."

if [ "$#" -eq "0" -o \( "$1" != "release" -a "$1" != "debug" -a -z "`echo "$1" | grep ^-`" \) ]
then
	echo "USAGE: $0 <release|debug|\"<cargo flag>...\"> [cc flag]..."
	exit 1
fi
cargoflags="$1"
shift
buildtype="debug"
cflags="-g3 -Og"
case "$cargoflags" in
-*-release*)
	buildtype="release"
	;;
release)
	buildtype="release"
	cargoflags="--$cargoflags"
	;;
debug)
	cargoflags=""
	;;
esac
if [ "$buildtype" = "release" ]
then
	cflags="-O2"
fi

cd "`dirname "$0"`"
cd "$LIBINGER"

set -ve
./configure || true
mkdir -p "target/$buildtype"
cargo run $cargoflags >"target/$buildtype/libinger.h"
rm "target/$buildtype/deps/libinger.so"
cd -
c99 $cflags -Wall -Wextra -Wpedantic -Werror "$@" -c -fpic -fno-optimize-sibling-calls -D_DEFAULT_SOURCE -I"$OLDPWD/target/$buildtype" testinger.c
cd -
cargo rustc $cargoflags --lib -- -Clink-arg="$OLDPWD/testinger.o"
cd -
mv "$OLDPWD/target/$buildtype/libinger.so" libtestinger.so
rm "$OLDPWD/target/$buildtype/deps/libinger.so"
rm testinger.o
cd -
./configure >/dev/null || true
